"use strict";
let places = ["cape town", "canada", "new york", "faislabad", "london"];
console.log("Original order:", places);
console.log("Alphabetical order:", [...places].sort());
console.log("Original order:", places);
console.log("Reverse Alphabetical order:", [...places].sort().reverse());
console.log("Original order:", places);
console.log("Reverse order:", places.reverse());
console.log("Original order:", places.reverse());
console.log("Alphabetical order:", places.sort());
console.log("Reverse Alphabetical order:", [...places].sort().reverse());
//console.log('original :' +  places);
//console.log('copy :' + [...places].sort().reverse());
//console.log('copy :' + [...places].sort().reverse());
//console.log('copy :' + [...places].sort());
//console.log('copy :' + [...places].sort().reverse());
