"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
let car = 'subaru';
console.log("Is car == 'subaru'? I predict True.");
console.log(car == 'subaru');
console.log("Is car === 'subaru'? I predict True.");
console.log(car === 'subaru');
console.log("Is car != 'subaru'? I predict False.");
console.log(car != 'subaru');
console.log("Is car !== 'subaru'? I predict False.");
console.log(car !== 'subaru');
console.log("Is car < 'subaru'? I predict False.");
console.log(car < 'subaru');
console.log("Is car > 'subaru'? I predict False.");
console.log(car > 'subaru');
console.log("Is car <= 'subaru'? I predict True.");
console.log(car <= 'subaru');
console.log("Is car >= 'subaru'? I predict True.");
console.log(car >= 'subaru');
console.log("Is car? I predict True.");
console.log(car);
